# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nornsctl < Formula
  desc "CLI for the Norns durable agent runtime"
  homepage "https://github.com/nornscode/nornsctl"
  version "0.4.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nornscode/nornsctl/releases/download/v0.4.2/nornsctl_darwin_amd64.tar.gz"
      sha256 "94211b68603e471f599a124527e547359b36eb2ef47f00207cf49035d203290c"

      define_method(:install) do
        bin.install "nornsctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nornscode/nornsctl/releases/download/v0.4.2/nornsctl_darwin_arm64.tar.gz"
      sha256 "ffd40359799b247b47f5263c9b6ebf083348755edefccea2119d2a1d22d71830"

      define_method(:install) do
        bin.install "nornsctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nornscode/nornsctl/releases/download/v0.4.2/nornsctl_linux_amd64.tar.gz"
      sha256 "0dc9c36eabe32f4808fc5e5593d87b95c1dab42c025888af594475dfda966014"
      define_method(:install) do
        bin.install "nornsctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nornscode/nornsctl/releases/download/v0.4.2/nornsctl_linux_arm64.tar.gz"
      sha256 "26b9228c00b4012c4f0203712c7d28858d129da5f3bed4042f2a7d2acfecd82d"
      define_method(:install) do
        bin.install "nornsctl"
      end
    end
  end
end
